### ISSUE TITLE
triggered alert shortcut doesnt work

### ISSUE THREAD

**Issue by stevecookform3** [jonboydell/logzio_terraform_provider#30]
From logz support:
>We noticed the alerts created via API have “groupByAggregationFields”: null, while it should be “groupByAggregationFields”: [],

this causes the triggered alert link (the one that says 'view in kibana' to fail (you get an error from logz 'unable to fetch logs').

issue seems to be this line:

https://github.com/jonboydell/logzio_terraform_provider/blob/2d8f454310369b197d866d1808d1ac6638098e75/logzio/resource_alert.go#L210

**Comment by jonboydell** [comment]
fixed in #31 - mistakenly duplicated the issue

**Comment by jonboydell** [comment]
proper SIT will be done tommorow

**Comment by pengux** [comment]
Hey @jonboydell, just checking if you need any further help with this fix, then please let me know.
